- name: Ensure kernel modules are added to /etc/modules
  ansible.builtin.lineinfile:
    state: present
    path: /etc/modules
    line: "{{ item }}"
  loop:
    - "ip_vs"
    - "ip_vs_rr"
    - "ip_vs_wrr"
    - "ip_vs_sh"
    - "br_netfilter"
    - "nf_conntrack"

- name: Restart systemd service to load modules
  ansible.builtin.service:
    state: restarted
    name: "systemd-modules-load.service"

- name: Add kernel module parameters configuration
  ansible.builtin.copy:
    content: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
      net.bridge.bridge-nf-call-iptables=1
      net.ipv4.ip_forward=1
    dest: /etc/sysctl.d/10-kubernetes.conf
    mode: "644"

- name: Reload kernel parameters using sysctl
  changed_when: true
  ansible.builtin.command:
    cmd: "sysctl --system"
