- name: Ensure haproxy is installed
  ansible.builtin.apt:
    update_cache: true
    state: present
    name: haproxy

- name: Add firewall rule to allow API traffic
  community.general.ufw:
    state: enabled
    rule: allow
    proto: tcp
    to_port: 6443

- name: Copy haproxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.t2
    dest: /etc/haproxy/haproxy.cfg
    mode: "644"

- name: Restart haproxy service
  ansible.builtin.service:
    state: restarted
    name: haproxy
