- name: Add nodes to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[node]['ansible_host'] }} {{ node }}"
  loop: "{{ groups['all'] }}"
  loop_control:
    loop_var: node
