- name: Prepare nodes
  hosts: all
  become: true
  tags: setup
  pre_tasks:
    - name: Disable firewall
      community.general.ufw:
        state: disabled
  roles:
    - kernel-modules
    - binaries
    - dns

- name: Create certificates and kubeconfigs
  hosts: controlplane01
  tags: certificates
  roles:
    - ca-cert
    - kubeconfig

- name: Distribute the certificates and kubeconfigs
  hosts: all
  tags: certificates
  tasks:
    - name: Copy all keys and certificates to control plane nodes
      when: inventory_hostname in groups['controlplane']
      block:
        - name: Copy all keys and certificates to controlplane nodes
          with_fileglob:
            - "certs/*.crt"
            - "certs/*.key"
          ansible.builtin.copy:
            src: "{{ item }}"
            dest: "~/{{ item | regex_replace('.*/(.*)$', '\\1') }}"
            mode: "644"
        - name: Copy kubeconfig files for controlplane components
          loop:
            - admin
            - kube-scheduler
            - kube-controller-manager
          ansible.builtin.copy:
            src: "kubeconfig/{{ item }}.kubeconfig"
            dest: "~/{{ item }}.kubeconfig"
            mode: "644"

    - name: Copy files to worker nodes
      when: inventory_hostname in groups['nodes']
      block:
        - name: Copy CA certificate and kube-proxy credentials to worker
          loop:
            - ca.crt
            - kube-proxy.crt
            - kube-proxy.key
          ansible.builtin.copy:
            src: "certs/{{ item }}"
            dest: "~/{{ item }}"
            mode: "644"
        - name: Copy kube-proxy config to nodes
          ansible.builtin.copy:
            src: kubeconfig/kube-proxy.kubeconfig
            dest: ~/kube-proxy.kubeconfig
            mode: "644"

- name: Configure the control plane components
  hosts: controlplane
  become: true
  tags:
    - controller
  roles:
    - etcd
    - controller

- name: Configure the load balancer
  hosts: loadbalancer
  become: true
  tags:
    - loadbalancer
  roles:
    - haproxy

- name: Install CRI workers
  hosts: nodes
  become: true
  tags:
    - cri
    - worker
  roles:
    - containerd
    - worker

- name: Configure cluster
  hosts: controlplane01
  tags:
    - pod-networking
    - apiserver-to-kubelet
    - coredns
  roles:
    - flannel
    - kubelet-rbac
    - coredns
    - default-kubeconfig
